
name: azan_flutter
description: Simple Azan player (Android-only)

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  file_picker: ^8.0.6
  adhan_dart: ^2.0.0
  intl: ^0.19.0

flutter:
  uses-material-design: true
