name: Build Android APK

on:
  workflow_dispatch:
  push:
    paths:
      - '*.zip'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip project
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          rm -rf AzanApp
          unzip *.zip -d AzanApp
          ls -la AzanApp

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: "34.0.0"

      - name: Make gradlew executable
        run: chmod +x AzanApp/gradlew

      - name: Build debug APK
        working-directory: AzanApp
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: AzanApp-debug-apk
          path: AzanApp/app/build/outputs/apk/debug/*.apk
