
name: Flutter Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Bootstrap Flutter project
        run: |
          if [ ! -d "android" ]; then
            flutter create . --platforms=android --org com.abdulwahhab --project-name azan_flutter
          fi

      - name: Apply native overrides
        run: |
          mkdir -p android/app/src/main/kotlin/com/abdulwahhab/azan
          rsync -a native_overrides/kotlin/ android/app/src/main/kotlin/
          cp native_overrides/manifest/AndroidManifest.xml android/app/src/main/AndroidManifest.xml
          echo "Applied overrides"

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: azan-flutter-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
